package postgres

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rohit-bagade/notifyx/internal/domain"
)

// NotificationRepository handles all DB operations for the notifications table.
// pool is an Executor (not *pgxpool.Pool directly) so the same repository type
// can also be constructed against a transaction — see WithTx in db.go.
type NotificationRepository struct {
	pool Executor
}

func NewNotificationRepository(pool Executor) *NotificationRepository {
	return &NotificationRepository{pool: pool}
}

// CreateNotificationParams holds the fields needed to persist a new notification.
type CreateNotificationParams struct {
	ID             uuid.UUID // generated by the caller so a dedup reservation can point at it before insert
	TenantID       uuid.UUID
	Channel        domain.Channel
	Priority       domain.Priority
	Status         domain.Status // empty defaults to "pending"
	RecipientID    string
	RecipientEmail string
	RecipientPhone string
	RecipientToken string
	TemplateID     *uuid.UUID // nil when the notification wasn't sent from a template
	Subject        string
	Body           string
	Metadata       map[string]any
	IdempotencyKey string     // empty stores NULL — multiple NULLs don't violate the unique constraint
	ScheduledAt    *time.Time // nil for immediate sends; set for deferred sends (Phase 9 scheduler)
}

func (r *NotificationRepository) Create(ctx context.Context, p CreateNotificationParams) (*domain.Notification, error) {
	if p.Metadata == nil {
		p.Metadata = map[string]any{}
	}
	if p.Status == "" {
		p.Status = domain.StatusPending
	}
	var idempotencyKey *string
	if p.IdempotencyKey != "" {
		idempotencyKey = &p.IdempotencyKey
	}

	row := r.pool.QueryRow(ctx,
		`INSERT INTO notifications
			(id, tenant_id, channel, priority, status, recipient_id, recipient_email, recipient_phone,
			 recipient_token, template_id, subject, body, metadata, idempotency_key, scheduled_at)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
		 RETURNING id, tenant_id, channel, priority, status, recipient_id, recipient_email, recipient_phone,
		           recipient_token, template_id, subject, body, metadata, idempotency_key, scheduled_at, created_at, expires_at`,
		p.ID, p.TenantID, string(p.Channel), string(p.Priority), string(p.Status), p.RecipientID, p.RecipientEmail,
		p.RecipientPhone, p.RecipientToken, p.TemplateID, p.Subject, p.Body, p.Metadata, idempotencyKey, p.ScheduledAt,
	)
	n, err := scanNotification(row)
	if err != nil {
		return nil, fmt.Errorf("create notification: %w", err)
	}
	return n, nil
}

func (r *NotificationRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	row := r.pool.QueryRow(ctx,
		`SELECT id, tenant_id, channel, priority, status, recipient_id, recipient_email, recipient_phone,
		        recipient_token, template_id, subject, body, metadata, idempotency_key, scheduled_at, created_at, expires_at
		 FROM notifications WHERE id = $1`,
		id,
	)
	n, err := scanNotification(row)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("get notification by id: %w", err)
	}
	return n, nil
}

// NotificationFilter narrows GetByTenantID — zero values mean "no filter" on that field.
type NotificationFilter struct {
	Channel   domain.Channel
	Status    domain.Status
	From      *time.Time
	To        *time.Time
	Limit     int
	Offset    int
	Recipient string
}

// GetByTenantID returns a page of notifications for tenantID along with the total
// matching row count (for pagination), newest first.
func (r *NotificationRepository) GetByTenantID(ctx context.Context, tenantID uuid.UUID, f NotificationFilter) ([]*domain.Notification, int, error) {
	rows, err := r.pool.Query(ctx,
		`SELECT id, tenant_id, channel, priority, status, recipient_id, recipient_email, recipient_phone,
		        recipient_token, template_id, subject, body, metadata, idempotency_key, scheduled_at, created_at, expires_at,
		        COUNT(*) OVER() AS total_count
		 FROM notifications
		 WHERE tenant_id = $1
		   AND ($2 = '' OR channel = $2)
		   AND ($3 = '' OR status = $3)
		   AND ($4::timestamptz IS NULL OR created_at >= $4)
		   AND ($5::timestamptz IS NULL OR created_at <= $5)
		   AND ($8 = '' OR
		        recipient_id ILIKE '%' || $8 || '%' OR
		        recipient_email ILIKE '%' || $8 || '%' OR
		        recipient_phone ILIKE '%' || $8 || '%' OR
		        recipient_token ILIKE '%' || $8 || '%')
		 ORDER BY created_at DESC
		 LIMIT $6 OFFSET $7`,
		tenantID, string(f.Channel), string(f.Status), f.From, f.To, f.Limit, f.Offset, f.Recipient,
	)
	if err != nil {
		return nil, 0, fmt.Errorf("list notifications: %w", err)
	}
	defer rows.Close()

	var notifications []*domain.Notification
	var total int
	for rows.Next() {
		n, err := scanNotification(rows, &total)
		if err != nil {
			return nil, 0, fmt.Errorf("scan notification: %w", err)
		}
		notifications = append(notifications, n)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterate notifications: %w", err)
	}
	return notifications, total, nil
}

// GetByStatus returns up to limit notifications with the given status, oldest first.
// Used by the rate-limit replayer to find queued_rate_limited notifications across all tenants.
func (r *NotificationRepository) GetByStatus(ctx context.Context, status domain.Status, limit int) ([]*domain.Notification, error) {
	rows, err := r.pool.Query(ctx,
		`SELECT id, tenant_id, channel, priority, status, recipient_id, recipient_email, recipient_phone,
		        recipient_token, template_id, subject, body, metadata, idempotency_key, scheduled_at, created_at, expires_at
		 FROM notifications WHERE status = $1 ORDER BY created_at ASC LIMIT $2`,
		string(status), limit,
	)
	if err != nil {
		return nil, fmt.Errorf("get notifications by status: %w", err)
	}
	defer rows.Close()

	var notifications []*domain.Notification
	for rows.Next() {
		n, err := scanNotification(rows)
		if err != nil {
			return nil, fmt.Errorf("scan notification: %w", err)
		}
		notifications = append(notifications, n)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate notifications: %w", err)
	}
	return notifications, nil
}

// UpdateStatus sets the notification's top-level status. Called by channel consumers
// (Phase 6+) as a delivery attempt resolves, and by the rate-limit replayer once a
// queued_rate_limited notification clears its window.
func (r *NotificationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.Status) error {
	tag, err := r.pool.Exec(ctx, `UPDATE notifications SET status = $1 WHERE id = $2`, string(status), id)
	if err != nil {
		return fmt.Errorf("update notification status: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// DeleteExpired removes notifications past their expires_at retention window (Phase 9
// daily cleanup cron). Deliveries cascade-delete via the notifications FK.
func (r *NotificationRepository) DeleteExpired(ctx context.Context, now time.Time) (int64, error) {
	tag, err := r.pool.Exec(ctx, `DELETE FROM notifications WHERE expires_at < $1`, now)
	if err != nil {
		return 0, fmt.Errorf("delete expired notifications: %w", err)
	}
	return tag.RowsAffected(), nil
}

// scanNotification scans the standard 17-column notification row shape shared by Create,
// GetByID, GetByTenantID, and GetByStatus. extra holds destinations for any additional
// columns a query selects beyond that shape (e.g. GetByTenantID's COUNT(*) OVER()).
func scanNotification(row pgx.Row, extra ...any) (*domain.Notification, error) {
	var n domain.Notification
	var channel, priority, status string
	var idempotencyKey *string

	dest := []any{
		&n.ID, &n.TenantID, &channel, &priority, &status, &n.RecipientID, &n.RecipientEmail, &n.RecipientPhone,
		&n.RecipientToken, &n.TemplateID, &n.Subject, &n.Body, &n.Metadata, &idempotencyKey, &n.ScheduledAt,
		&n.CreatedAt, &n.ExpiresAt,
	}
	dest = append(dest, extra...)

	if err := row.Scan(dest...); err != nil {
		return nil, err
	}

	n.Channel = domain.Channel(channel)
	n.Priority = domain.Priority(priority)
	n.Status = domain.Status(status)
	if idempotencyKey != nil {
		n.IdempotencyKey = *idempotencyKey
	}
	return &n, nil
}
