package middleware

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/rohit-bagade/notifyx/pkg/logger"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"go.uber.org/zap/zaptest/observer"
)

// newObservedLogger builds a *logger.Logger backed by zap's observer core, so tests can
// assert on emitted log entries without depending on stdout/stderr formatting.
func newObservedLogger() (*logger.Logger, *observer.ObservedLogs) {
	core, logs := observer.New(zapcore.DebugLevel)
	zl := zap.New(core)
	return &logger.Logger{SugaredLogger: zl.Sugar()}, logs
}

func TestRequestLogger_SuccessLogsInfo(t *testing.T) {
	log, logs := newObservedLogger()
	mw := RequestLogger(log)

	e := echo.New()
	req := httptest.NewRequest(http.MethodGet, "/foo", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)

	handler := mw(func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"ok": "true"})
	})

	err := handler(c)
	require.NoError(t, err)

	entries := logs.All()
	require.Len(t, entries, 1)
	require.Equal(t, zapcore.InfoLevel, entries[0].Level)
	require.Equal(t, "http request", entries[0].Message)

	fields := entries[0].ContextMap()
	require.Equal(t, "GET", fields["method"])
	require.Equal(t, "/foo", fields["path"])
	require.EqualValues(t, http.StatusOK, fields["status"])
}

func TestRequestLogger_HandlerErrorLogsError(t *testing.T) {
	log, logs := newObservedLogger()
	mw := RequestLogger(log)

	e := echo.New()
	req := httptest.NewRequest(http.MethodGet, "/bar", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)

	handlerErr := errors.New("boom")
	handler := mw(func(c echo.Context) error {
		return handlerErr
	})

	err := handler(c)
	require.Error(t, err)

	entries := logs.All()
	require.Len(t, entries, 1)
	require.Equal(t, zapcore.ErrorLevel, entries[0].Level)
	require.Equal(t, "http request failed", entries[0].Message)

	fields := entries[0].ContextMap()
	require.Equal(t, "GET", fields["method"])
	require.Equal(t, "/bar", fields["path"])
	require.Equal(t, "boom", fields["error"])
}

func TestRequestLogger_UncommittedRouterError_StatusReflectsErrorHandling(t *testing.T) {
	// Simulates a 404/405 generated by Echo's router itself, which bypasses every
	// handler and arrives here with the response not yet committed. RequestLogger
	// should call c.Error(err) so the status reflects the failure even though no
	// handler ever wrote to the response.
	log, logs := newObservedLogger()
	mw := RequestLogger(log)

	e := echo.New()
	e.HTTPErrorHandler = func(err error, c echo.Context) {
		c.JSON(http.StatusNotFound, map[string]string{"error": err.Error()})
	}
	req := httptest.NewRequest(http.MethodGet, "/missing", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)

	notFoundErr := echo.NewHTTPError(http.StatusNotFound, "not found")
	handler := mw(func(c echo.Context) error {
		return notFoundErr
	})

	err := handler(c)
	require.Error(t, err)
	require.Equal(t, http.StatusNotFound, rec.Code)

	entries := logs.All()
	require.Len(t, entries, 1)
	require.Equal(t, zapcore.ErrorLevel, entries[0].Level)
	fields := entries[0].ContextMap()
	require.EqualValues(t, http.StatusNotFound, fields["status"])
}
